all:
  children:
    bastion:
      hosts:
        okd-boot.example.com:
      vars:
        ansible_user: ansible
    management:
      hosts:
        okd01.example.com:
        okd02.example.com:
        okd03.example.com:
      vars:
        ansible_user: ansible
    compute:
      hosts:
        okd04.example.com:
        okd05.example.com:
        okd06.example.com:
      vars:
        ansible_user: ansible
